### ISSUE TITLE
Can't type in input boxes

### ISSUE THREAD

**Issue by Altersplatz** [OfficialAaRat-RRI/ARTG-Official-Web#2]
1) Can't type in input boxes.
2) Sign Up Box doesn't shows up. 

@CodyAaTherf

**Comment by CodyAaTherf** [comment]
Can you explain it in detail?

**Comment by Altersplatz** [comment]
uhh the sign in box is like blurred out and unable to type in. Something with the CSS prob , and the sign up box doesn't show's up.

**Comment by CodyAaTherf** [comment]
Alright I'll look into it.

**Comment by Altersplatz** [comment]
Okay.

**Comment by CodyAaTherf** [comment]
Fixed.
